// Autogenerated template for Firebase configuration.
// Replace the placeholder values with the real ones from your Firebase console
// or run `flutterfire configure` locally to generate a complete `firebase_options.dart`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Adjust logic if you want platform-specific options.
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDz18k-2rZ1yiy1Msj8BXox9sWr1qQTOjQ',
  appId: '1:27380424123:android:REPLACE_WITH_APP_ID',
  messagingSenderId: '27380424123',
  projectId: 'uruaapan-6f3ef',
  storageBucket: 'uruaapan-6f3ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDz18k-2rZ1yiy1Msj8BXox9sWr1qQTOjQ',
  appId: '1:27380424123:ios:REPLACE_WITH_APP_ID',
  messagingSenderId: '27380424123',
  projectId: 'uruaapan-6f3ef',
  storageBucket: 'uruaapan-6f3ef.firebasestorage.app',
    iosClientId: '',
    iosBundleId: '',
  );

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDz18k-2rZ1yiy1Msj8BXox9sWr1qQTOjQ',
  appId: '1:27380424123:web:07505a95a2f4fd683f789e',
    messagingSenderId: '27380424123',
  projectId: 'uruaapan-6f3ef',
  authDomain: 'uruaapan-6f3ef.firebaseapp.com',
  storageBucket: 'uruaapan-6f3ef.firebasestorage.app',
  measurementId: 'G-1LH8Y2R4NW',
  );
}
